const Head = () => {
  return (
    <>
      <title>Cat Book</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/cat.ico" />
    </>
  );
};
